version: '3.8'

services:
  nutrimatch-api:
    build: .
    container_name: nutrimatch-container
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
